### ISSUE TITLE
The repo doesn't seem to work when port is set in .env

### ISSUE THREAD

**Issue by developomp** [elibolonur/ts-express-vue3#2]
How to reproduce:
1.) Clone the repo
2.) Install dependencies `npm i`
3.) Add `PORT=XXXX` to `.env`
4.) Serve the app `npm run serve`

Expected: Shows vue app

What happens:
shows
```
{"title":"Boilerplate for Express + Vue.JS with Typescript"}
```
as raw text.

This seems to be the case for any port including the port 3000 (the default port).

**Comment by elibolonur** [comment]
Thanks for reporting.

I see the problem, both webpack dev server and express are reading the `PORT` variable. Defining server port as another variable should solve the issue.

fe34bfa3e9b44dec85659b042833365865f93c42 solves the problem, server part now uses `SERVER_PORT` variable.
